# Generated by Django 2.0.13 on 2020-07-08 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Board',
            new_name='Page',
        ),
    ]
